[package]
name = "libharu-rs"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libharu-sys = "0.0.1"
libc = "0.2.100"
dispose = "0.3.1"
